#!/usr/bin/env node
/**
 * Lädt die benötigten Schriftarten von Google Fonts herunter und speichert sie
 * lokal in `assets/fonts/`. Erzeugt damit eine DSGVO-konforme Self-Hosted-Variante
 * — keine Verbindung mehr zu Google-Servern beim Aufruf der Webseite.
 *
 * Aufruf:
 *   node tools/download-fonts.mjs
 *
 * Vorausgesetzt: Node 18+ (für globales fetch).
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, resolve, join } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = join(root, 'assets', 'fonts');
mkdirSync(fontsDir, { recursive: true });

// User-Agent simuliert modernen Chrome — wichtig, damit Google Fonts woff2 ausliefert.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
          '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Schriftarten, die die Hauptseiten nutzen.
const fonts = [
  {
    family: 'Fraunces',
    cssUrl: 'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT@9..144,300..700,30..100&display=swap',
    outName: 'fraunces',
    variable: true,
  },
  {
    family: 'Inter',
    cssUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap',
    outName: 'inter',
  },
  {
    family: 'JetBrains Mono',
    cssUrl: 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap',
    outName: 'jetbrains-mono',
  },
  {
    // Script-Schrift für die "schneiderei"-Wortmarke im Logo-Schriftzug
    family: 'Allura',
    cssUrl: 'https://fonts.googleapis.com/css2?family=Allura&display=swap',
    outName: 'allura',
  },
];

console.log('📦  Downloading fonts to assets/fonts/…\n');

let combinedCss = '/* Generated by tools/download-fonts.mjs — do not edit manually */\n\n';

for (const f of fonts) {
  console.log(`  → ${f.family}`);
  const cssRes = await fetch(f.cssUrl, { headers: { 'User-Agent': UA }});
  if (!cssRes.ok) {
    console.error(`    ✗ Failed to fetch CSS (${cssRes.status})`);
    continue;
  }
  let css = await cssRes.text();

  // Alle woff2-URLs aus der zurückgelieferten CSS extrahieren.
  const matches = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)];
  console.log(`    found ${matches.length} woff2 file(s)`);

  let counter = 1;
  for (const m of matches) {
    const url = m[1];
    const filename = `${f.outName}-${String(counter).padStart(2,'0')}.woff2`;
    const outPath = join(fontsDir, filename);

    if (!existsSync(outPath)) {
      const fontRes = await fetch(url);
      if (!fontRes.ok) { console.warn(`      ✗ ${url}`); continue; }
      const buf = Buffer.from(await fontRes.arrayBuffer());
      writeFileSync(outPath, buf);
    }
    css = css.split(url).join(`fonts/${filename}`);
    counter++;
  }

  // Den 'src: url(https://fonts.gstatic.com/…)'-Pfad durch lokalen relativen Pfad ersetzen
  combinedCss += `/* === ${f.family} === */\n` + css.trim() + '\n\n';
  console.log(`    ✓ saved ${counter - 1} files`);
}

// Sammel-CSS ablegen: assets/fonts.css
const fontsCssPath = join(root, 'assets', 'fonts.css');
writeFileSync(fontsCssPath, combinedCss);

console.log(`\n✅  Done.`);
console.log(`    • Fonts liegen unter assets/fonts/`);
console.log(`    • @font-face-Deklarationen unter assets/fonts.css`);
console.log(`    • assets/style.css importiert fonts.css bereits via @import.`);
console.log(`\n💡  Deploy-Tipp: Cache-Header auf .woff2-Dateien setzen (z.B. 1 Jahr).`);
